name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm test

      - name: Start backend
        working-directory: backend
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm start &

      - name: Start frontend
        working-directory: frontend
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm start &

      - name: Wait for services to start
        run: sleep 30

      - name: Run Cypress tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          cd frontend
          npx cypress run

      - name: Stop backend and frontend
        run: |
          pkill -f 'node server.js'
          pkill -f 'react-scripts'
